name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbdev
          pip install -e ".[dev]"

      - name: Clean notebooks
        run: |
          nbdev_clean

      - name: Export notebooks
        run: |
          nbdev_export

      - name: Run tests
        run: |
          python -c "import sys; print(f'Python version: {sys.version}')"
          python -c "import logging; logging.basicConfig(level=logging.DEBUG); logging.debug('Logging test')"
          PYTHONPATH=. python -m nbdev.test --help
          PYTHONPATH=. nbdev_test --do_print --timing -v