name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: test stuff
        run: |
          pwd
          mkdir -p data/tutu
          ls
          ls /tmp

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install nbdev
      #     pip install -e ".[dev]"

      # - name: Clean notebooks
      #   run: |
      #     nbdev_clean

      # - name: Export notebooks
      #   run: |
      #     nbdev_export

      # - name: Run tests
      #   env:
      #     PYTHONPATH: .
      #     LOGGING_LEVEL: DEBUG
      #   run: |
      #     nbdev_test --do_print --timing

      # - name: Display log file
      #   run: |
      #     cat nbdev_test_log.txt || echo "No log file found"

      # - name: Display diagnostic log
      #   run: |
      #     cat nbdev_diagnostic_log.txt || echo "No diagnostic log file found"