name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          pip install pytest
      
      - name: Run tests with verbose output
        run: |
          pytest -v
          
      - name: Print additional diagnostic information
        run: |
          python -c "import sys; print(f'Python version: {sys.version}')"
          pip list
